apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"app":"web-server"},"name":"web-server","namespace":"default"},"spec":{"replicas":5,"selector":{"matchLabels":{"app":"web-server"}},"strategy":{},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"web-server"}},"spec":{"containers":[{"image":"nginxdemos/hello","name":"nginx","ports":[{"containerPort":80}],"resources":{}}]}}},"status":{}}
  creationTimestamp: "2023-05-26T17:45:52Z"
  generation: 2
  labels:
    app: web-server
  name: web-server
  namespace: default
  resourceVersion: "75469"
  uid: 5ec08b05-37bd-46ff-80ba-06f5dc00287d
spec:
  progressDeadlineSeconds: 600
  replicas: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: web-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        date: "1685124701"
      creationTimestamp: null
      labels:
        app: web-server
    spec:
      containers:
      - image: nginxdemos/hello
        imagePullPolicy: Always
        name: web-server
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 5
  conditions:
  - lastTransitionTime: "2023-05-26T17:51:26Z"
    lastUpdateTime: "2023-05-26T17:51:26Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-05-26T17:45:52Z"
    lastUpdateTime: "2023-05-26T17:51:33Z"
    message: ReplicaSet "web-server-f457599dc" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 5
  replicas: 5
  updatedReplicas: 5
