apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web-server
  namespace: default
  labels:
    app: web-server
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
        - name: web-server
          image: nginxdemos/hello
          ports: 
          - containerPort: 80