apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
  - name: wordpress
    port: 80
    targetPort: 80
    nodePort: 30105
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:latest
          env:
            - name: WORDPRESS_DB_HOST
              value: wordpress-mysql
              # valueFrom:
              #   configMapKeyRef:
              #     name:  myconfigmap
              #     key: WORDPRESS_DB_HOST
            - name: WORDPRESS_DB_USER
              value: root
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: root_password
          ports:
            - containerPort: 80
              name: wordpress
# apiVersion: batch/v1beta1
# kind: CronJob
# metadata:
#   name: hello
#   namespace: default
# spec:
#   schedule: "*/1 * * * *"
#   jobTemplate:
#     spec:
#       template:
#         spec:
#           containers:
#           - name: hello
#             image: busybox
#             args: ['/bin/sh', '-c', 'date; echo Hello from the Kubernetes cluster']
#           restartPolicy: OnFailure


#kubectl apply -f https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.13.1/controller.yaml
#kubectl wait --for condition=established crd sealedsecrets.bitnami.com
#kustomize build . | kubectl apply -f -